### ISSUE TITLE
Add Step (?): allow dev to assert which page ids or trigger vars were visited or not. Maybe in what order as well.

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#631]
[Will this actually be used? From experience, most people are probably going to use the random input Step. If we update that to track page ids and/or trigger vars, they might make use of it, but it too might just take too much work for people to use it.]

For example, something like:

```
Then the user saw these pages
  """
    user name
    user role
    other parties
  """
```

and:

```
Then the user did NOT see these pages
  """
    children name
    children lawyer name
  """
```

and possibly (though we have to figure out if it's actually useful):

```
Then the user saw these pages in this order
  """
    user name
    user address
  """
```

With this last one, should they be able to skip listing pages so they don't have to write out every single id? Maybe have a different Step that says "Then the user saw these pages in this order without skipping pages"? Maybe:

```
Then the user saw the page "user address" sometime/right after the page "user name"
```

Also have a Step for "before"?

**Comment by BryceStevenWilley** [comment]
I'm not sure I understand the benefit of listing pages in the same order. For ordering screens, I've found it much more useful to list each step separately (even if it's a lot of steps, and you have to explicitly say to continue), because it's really easy at a glance to know which step a test fails at, something that is difficult on steps that cover multiple screens like tables.

I see how "user did not see these pages" could be useful, but I thought through it a bit, and given that:
* it would likely come after a story table
* if it's something you don't want to enter info on, the info could just not be present in the story table. So this step would be useful if there are other screens (gathering the same variables) that could show up instead of the desired one
* New bugs in this case are likely to be newly added screens, with different ids than the ones you are already trying to avoid.

I feel like I'd end up recommending people use the "user did see these pages" step instead, which is a lot stricter than than the "Not see" step.

Let me know if I'm misunderstanding anything here, I might be missing a really useful case to have these steps.
