### ISSUE TITLE
Show a clearer error when the node installation at the start of the action fails

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#667]
It's been failing a few times in the last couple of days and we don't have a good way to put it in the documentation. If we can write our own error for that, we can document it. Not sure how failure works in actions - if one fails, do they all fail? [Answer: You can add an `if: always()` and such to run steps even after failure.]

**Comment by BryceStevenWilley** [comment]
To add some more info, are you talking about failures like https://github.com/SuffolkLITLab/docassemble-ALWeaver/actions/runs/4441022073/jobs/7795564484? Where there's an `Unexpected HTTP response: 404`?  Not that it matters much but I did track it down to [this line] in setup-node v1, which leads to https://nodejs.org/dist/index.json. The `nodejs.org` site seems to [have had some problems on Friday](https://github.com/nodejs/nodejs.org/issues/5149). I'm not sure about longer term fixes on our side; It's a rare enough thing and we don't have any work arounds besides for "run it again", so I don't think it should be in the docs. And we can't really predict how various node services below us will fail, so I'm not sure about putting effort towards better error handling in things we should assume work.

> Not sure how failure works in actions - if one fails, do they all fail?

I believe so; in the linked job above, it tries to run takedown, but it fails because node never even installed.

**Comment by plocket** [comment]
I mean I'd like to provide our users (and future us) with clearer info on what happened when node failed so we don't have to explain it. If we made a good error message, maybe we wouldn't even need to document. You might be right about it being too rare to bother with, but it happened two or three times over the course of two days, which did concern me a bit. Maybe it's just a matter of a screenshot and documenting the `404`. It might also be a good task for someone who doesn't want to learn all of our codebase.
