### ISSUE TITLE
Timezone mismatch between GitHub action runner and Interview Server

### ISSUE THREAD

**Issue by BryceStevenWilley** [plocket/docassemble-cucumber#762]
For some timezones at certain points of the day, `today` differs on the GitHub action runner (where the Kiln JS code is running), from `today` on the interview server (where the selection of the day actually happens). This results in the wrong day being chosen (one day earlier than it should be, as from the interview server perspective, the GitHub runner is "in the future").

https://github.com/SuffolkLITLab/ALKiln/blob/fb7bb3b38ab6a18940eca6a51fbef8339e12563c/lib/scope.js#L1742 is the relevant line of code. Which is fine, but it's the only part of the `today` code that relies on server state and isn't just math.

The best fix I can think of is just update the timezone in the GitHub to match the interview server's timezone, https://github.com/marketplace/actions/set-timezone might be useful there.

**Comment by plocket** [comment]
A note that this has actually helped developers find problems with their interviews because of the timezone difference and it may be a common user problem. I'd be tempted to make the time zone 3 hours ahead of the developer's timezone. Maybe that should be a developer opt-out env var. Opt-out because if they have a problem they may go to the docs, where we should add more details about timezone problems (we have a bit there already, I think).
